services:
  api:
    image: api_load_test:latest
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      DB_HOST: postgres_db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres2025
      DB_NAME: test_lb
    networks:
      - my_network
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres2025
      POSTGRES_DB: test_lb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network
    ports:
      - "5432:5432"
    restart: always

volumes:
  postgres_data:

networks:
  my_network:
